### ISSUE TITLE
Plan fails when enabled set to false

### ISSUE THREAD

**Issue by januaryjon** [cloudposse/terraform-aws-elasticache-memcached#45]
## Describe the Bug
When using this module in an workspace, but setting the `enabled` flag to `false`, running a `terraform plan` for the workspace will result in the following error:

```
Error: Invalid function argument

on .terraform/modules/memcached_setting_apigw/outputs.tf line 12, in output "security_group_arn":
12:   value       = join("", module.aws_security_group.*.arn)
  module.aws_security_group is object with 4 attributes

Invalid value for "lists" parameter: element 0 is null; cannot concatenate
null values.
```

## Expected Behavior
Terraform plan should run successfully without creating any resources

## Steps to Reproduce
1. Create an new terraform workspace with aws provider
2. Add this module to the workspace, use one of the following methods for security group configuration:
    - allowed_cidr_blocks
    - allowed_ipv6_cidr_blocks
    - allowed_ipv6_prefix_list_ids
    - allowed_security_groups
3. Disable this module (set `enabled=false` for this module)

## Environment

- Terraform version: v1.1.8
- AWS provider: v4.8.0

**Comment by z0rc** [comment]
Same issue when `create_security_group = false`.

**Comment by dmytrozhivotovsky** [comment]
I think I found a way to fix it:
https://github.com/cloudposse/terraform-aws-elasticache-memcached/pull/49/commits/e1f9f29be570ef9d0e84961d05e2866b382dcbab
